required = ["golang.org/x/tools", "golang.org/x/text"]

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"

[[constraint]]
  name = "golang.org/x/image"
  branch = "master"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"
