version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/
    steps:
      - run:
          name: Install dep
          command: |
            go get -u github.com/golang/dep/cmd/dep
      - checkout
      - run:
          command: pwd
      - run: 
          name: Resolving dependency
          command: |
            dep ensure
      - run: go list ./...
      - run: go test -v $(go list ./...)