version: 2
jobs:
  build:
    docker:
      - image: golang:1.9.2
    working_directory: /go/src/github.com/gkasse/extSmaller
    steps:
      - run:
          name: Add GOPATH
          command: |
            ls -al /go/src
#            echo "export GOPATH=" > ${BASH_ENV}
      - restore_cache:
          keys:
            - source-{{ checksum "Gopkg.toml" }}
            - source-
      - checkout
      - run:
          name: Add GOPATH
          command: |
            ls -al /go/src
      - run:
          name: Initialization
          command: |
            make init
      - run:
          name: Add GOPATH
          command: |
            ls -al /go/src
      - save_cache:
          key: source-{{ checksum "Gopkg.toml" }}
          paths: 
            - "/go/src"
      - run:
          name: Do test
          command: |
            make ci-test
      - run:
          name: Build
          command: make build
      - store_artifacts:
          path: ./out
          when: always