version: 2
jobs:
  build:
    docker:
      - image: golang:1.9.2
    working_directory: /go/src/github.com/gkasse/extSmaller
    steps:
      - checkout
      - run:
          name: Initialization
          command: |
            make init
      - run:
          name: Do test
          command: |
            make ci-test
      - run:
          name: Build
          command: make build
      - store_artifacts:
          path: ./out
          when: always