version: 2
jobs:
  build:
    docker:
      - image: golang:1.9.2
    working_directory: /go/src/github.com/gkasse/extSmaller
    steps:
      - run: pwd
      - run:
          name: Install dep
          command: |
            go get -u github.com/golang/dep/cmd/dep
      - checkout
      - run: ls -ltr
      - run: pwd
      - run: 
          name: Resolving dependency
          command: |
            dep ensure
      - run: go list ./...
      - run: go test -v $(go list ./...)