version: 2
jobs:
  build:
    docker:
      - image: golang:1.9.2
    working_directory: /go/src/github.com/gkasse/extSmaller
    steps:
      - run:
          name: Install dep
          command: |
            go get -u github.com/golang/dep/cmd/dep
      - checkout
      - run: 
          name: Resolving dependency
          command: |
            dep ensure
      - run:
          name: Do test
          command: |
            go test -v $(go list ./...)
      - run:
          name: Build for mac
          command: |
           GOOS=darwin GOARCH=amd64 go build extSmaller.go
      - store_artifacts:
          path: ./extSmaller