version: 2
jobs:
  build:
    docker:
      - image: golang:1.9.2
    working_directory: /go/src/github.com/gkasse/extSmaller
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-v1-{{ checksum "Gopkg.toml" }}
            - vendor-v1-
      - run:
          name: Initialization
          command: |
            make init
      - save_cache:
          key: vendor-v1-{{ checksum "Gopkg.toml" }}
          paths: 
            - "./vendor"
      - run:
          name: Do test
          command: |
            make ci-test
      - run:
          name: Build
          command: make build
      - store_artifacts:
          path: ./out
          when: always